name: Node.js CI

on:
  schedule:
    - cron: '20 12 * * 1'  # Runs every Monday at 11:50 UTC
  workflow_dispatch:  # Enables manual runs for testing

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Print date and time
      run: date

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build --if-present

    - name: Install Playwright browsers
      run: npx playwright install

    - name: Run Playwright Tests
      run: xvfb-run --auto-servernum -- npx playwright test
      env:
        BASE_URL: ${{ secrets.BASE_URL }}  # Example of using environment variables

    - name: Check Current Time
      run: date
